[package]
name = "stringzilla"
version = "3.11.3"
authors = ["Ash Vardanian <1983160+ashvardanian@users.noreply.github.com>"]
description = "Search, hash, sort, fingerprint, and fuzzy-match strings faster via SWAR, SIMD, and GPGPU"
edition = "2021"
license = "Apache-2.0"
publish = true
repository = "https://github.com/ashvardanian/stringzilla"
documentation = "https://docs.rs/stringzilla"
homepage = "https://ashvardanian.com/posts/stringzilla/"
keywords = ["simd", "search", "retrieval", "hash", "sort"]
categories = [
    "text-processing",
    "hardware-support",
    "no-std",
    "wasm",
    "external-ffi-bindings",
]
include = ["/rust/**", "/c/**", "/include/**", "/build.rs"]

[lib]
name = "stringzilla"
path = "rust/stringzilla.rs"

[build-dependencies]
cc = "1.2.31"
